Repository dcos/dcos-ui, pull requests merged in 2018-05, with the labels that each got.

#2930 DCOS-22349: add gpu in nodes table
  plugins/nodes/src/js/components/NodesTable.js
  src/js/constants/NodesTableHeaderLabels.js
  src/js/utils/ResourcesUtil.js
  src/js/utils/__tests__/ResourcesUtil-test.js
Labels: hold merge

#2927 DCOS-22332 Graphql spec compliance for field values and aliases
  .eslintrc
  packages/data-service/src/__tests__/graphqlObservable-test.js
  packages/data-service/src/__tests__/reference/starWarsData.js
  packages/data-service/src/__tests__/reference/starWarsQuery-test.js
  packages/data-service/src/__tests__/reference/starWarsSchema.js
  packages/data-service/src/graphqlObservable.js
  plugins/catalog/src/js/repositories/RepositoriesList.js
Labels: data-layer, high priority

#2897 DCOS-23834 - Data Layer Reference Implementation
  .eslintrc
  npm-shrinkwrap.json
  package.json
  packages/data-service/.gitignore
  packages/data-service/LICENSE
  packages/data-service/package-lock.json
  packages/data-service/package.json
  packages/data-service/src/__tests__/graphqlObservable-test.js
  packages/data-service/src/__tests__/reference/starWarsData.js
  packages/data-service/src/__tests__/reference/starWarsQuery-test.js
  packages/data-service/src/__tests__/reference/starWarsSchema.js
  packages/data-service/src/graphqlObservable.js
  packages/data-service/src/index.js
  packages/data-service/src/recomposeRx.js
  plugins/catalog/src/js/repositories/RepositoriesAdd.js
  plugins/catalog/src/js/repositories/RepositoriesDelete.js
  plugins/catalog/src/js/repositories/RepositoriesList.js
  plugins/catalog/src/js/repositories/__tests__/repositoriesStream-test.js
  plugins/catalog/src/js/repositories/components/AddRepositoryFormModal.js
  plugins/catalog/src/js/repositories/components/RepositoriesDeleteConfirm.js
  plugins/catalog/src/js/repositories/components/RepositoriesError.js
  plugins/catalog/src/js/repositories/components/RepositoriesLoading.js
  plugins/catalog/src/js/repositories/components/RepositoriesPage.js
  plugins/catalog/src/js/repositories/components/RepositoriesTabUI.js
  plugins/catalog/src/js/repositories/components/RepositoriesTable.js
  plugins/catalog/src/js/repositories/data/repositoriesModel.js
  plugins/catalog/src/js/repositories/data/repositoriesStream.js
  src/js/events/CosmosPackagesActions.js
  src/js/events/__tests__/CosmosPackagesActions-test.js
  src/js/pages/system/RepositoriesTab.js
  src/js/routes/settings.js
Labels: data-layer, feature branch, high priority

#2952 DCOS-35757: remove 2 seconds timeout
  src/js/events/MesosStateActions.js
Labels: blocker

#2959 DCOS-37421: Adjust GetSetBaseStore to stop dispatching events on every change
  src/js/stores/ConfigStore.js
  src/js/stores/GetSetBaseStore.js
Labels: blocker

#2954 DCOS-37423: improve performance of composite store nodes list getter
  src/js/structs/CompositeState.js
Labels: blocker

#2956 DCOS-37422: adjust flagSDKTask to improve performance
  src/js/stores/MesosStateStore.js
Labels: blocker

#2961 DCOS-37436: Adjust mesos state store
  src/js/stores/MesosStateStore.js
  src/js/stores/__tests__/MesosStateStore-test.js
Labels: blocker

#2950 [Backport 1.11] fix(NestedServiceLinks): group link
  plugins/services/src/js/containers/services/ServicesTable.js
  src/js/components/NestedServiceLinks.js
  src/js/components/__tests__/NestedServiceLinks-test.js
Labels: blocker

#2949 fix(NestedServiceLinks): group link
  plugins/services/src/js/containers/services/ServicesTable.js
  src/js/components/NestedServiceLinks.js
  src/js/components/__tests__/NestedServiceLinks-test.js
Labels: high priority

#2970 DCOS-37461: Run assignSchedulerTaskField once
  src/js/stores/MesosStateStore.js
  src/js/stores/__tests__/MesosStateStore-test.js
Labels: blocker

#2973 DCOS-37475: Cache Service Tree
  src/js/stores/DCOSStore.js
  src/js/stores/__tests__/DCOSStore-test.js
Labels: blocker

#2962 DCOS-37556: prevent unnecessary updates in ServiceBreadcrumb
  plugins/services/src/js/components/ServiceBreadcrumbs.js
  plugins/services/src/js/components/__tests__/ServiceBreadcrumbs-test.js
Labels: high priority

#2974 [1.10] DCOS-37555: prevent unnecessary updates in ServiceBreadcrumb
  plugins/services/src/js/components/ServiceBreadcrumbs.js
Labels: high priority

#2982 [1.10] DCOS-37585: fix marathon health checks by caching right task data
  src/js/stores/DCOSStore.js
  src/js/stores/__tests__/DCOSStore-test.js
Labels: blocker

#2971 [1.11] DCOS-37554: prevent unnecessary updates in ServiceBreadcrumb
  plugins/services/src/js/components/ServiceBreadcrumbs.js
Labels: high priority

#2947 DCOS-22014: Add and remove repos with graphql mutations
  plugins/catalog/src/js/repositories/RepositoriesAdd.js
  plugins/catalog/src/js/repositories/RepositoriesDelete.js
  plugins/catalog/src/js/repositories/RepositoriesList.js
  plugins/catalog/src/js/repositories/__tests__/repositoriesModel-test.js
  plugins/catalog/src/js/repositories/data/repositoriesModel.js
Labels: data-layer, high priority

#2965 DCOS-37432 - [1.11] improve merge data
  plugins/services/src/js/containers/tasks/TasksView.js
  plugins/services/src/js/utils/TaskMergeDataUtil.js
  src/js/stores/DCOSStore.js
  src/js/stores/__tests__/DCOSStore-test.js
Labels: high priority

#2966 DCOS-37434- [master] improve merge data
  plugins/services/src/js/containers/pod-instances/PodInstancesContainer.js
  plugins/services/src/js/containers/pod-instances/PodInstancesView.js
  plugins/services/src/js/containers/tasks/TasksView.js
  plugins/services/src/js/utils/TaskMergeDataUtil.js
  src/js/stores/DCOSStore.js
  src/js/stores/__tests__/DCOSStore-test.js
Labels: high priority
