Repository dcos/dcos-ui, pull requests merged in 2018-03, with the labels that each got.

#2686 DCOS_OSS-2186: Upgrade node to 8.9
  .nvmrc
  CONTRIBUTING.md
  Dockerfile
  README.md
  npm-shrinkwrap.json
  package.json
  plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
  src/js/components/__tests__/JSONEditor-test.js
  webpack/webpack.config.babel.js
Labels: skip-ci

#2816 DCOS_OSS-2243: fix(taskdetails): remove misleading endpoints row from config table
  plugins/services/src/js/pages/task-details/TaskDetailsTab.js
Labels: high priority

#2786 DCOS-21305: Respect DC/OS min required version when installing a package.
  package.json
  src/js/pages/catalog/PackageDetailTab.js
  tests/_fixtures/dcos/dcos-version.json
  tests/pages/catalog/packages/PackagesTab-cy.js
Labels: high priority

#2834 DCOS-21190: hide service status if it's N/A
  plugins/services/src/js/containers/services/ServicesTable.js
  plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
  plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap
Labels: needs 1.11 PR

#2825 [Backport 1.11] DCOS-21305: Respect DC/OS min required version when installing a package.
  npm-shrinkwrap.json
  package.json
  src/js/pages/catalog/PackageDetailTab.js
  tests/_fixtures/dcos/dcos-version.json
  tests/pages/catalog/packages/PackagesTab-cy.js
Labels: high priority

#2836 feat(EditServiceModal): show cosmos services in json-schema form
  plugins/services/src/js/components/HighOrderServiceConfiguration.js
  plugins/services/src/js/components/modals/EditServiceModal.js
Labels: blocker

#2835 fix(FrameworkConfigurationForm): improve schema errors
  src/js/components/FrameworkConfigurationForm.js
  src/styles/components/framework-configuration/styles.less
Labels: high priority

#2796 Improve Jenkins pipeline
  Jenkinsfile
  Jenkinsfile.release
  scripts/ci/generate-changelog
  scripts/ci/update-github
  scripts/ci/upload-build
Labels: high priority

#2830 DCOS-21440: keep VIP label
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/components/forms/NetworkingFormSection.js
  plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
  plugins/services/src/js/reducers/serviceForm/Container.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/PortMappingsReducer.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
  plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
  plugins/services/src/js/reducers/serviceForm/PortMappings.js
  plugins/services/src/js/reducers/serviceForm/__tests__/PortMappings-test.js
  plugins/services/src/js/utils/VipLabelUtil.js
  plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js
Labels: hold merge

#2844 feat(package-describe): add fixture for x-region:string
  tests/_fixtures/cosmos/package-describe.json
Labels: blocker

#2848 DCOS-21766: fix(ci): fix release file name
  scripts/ci/upload-build
Labels: blocker

#2855 DCOS-19586 - (feat): volume table and volume detail for pods
  plugins/services/src/js/components/PodVolumeTable.js
  plugins/services/src/js/containers/pod-detail/PodDetail.js
  plugins/services/src/js/containers/volume-detail/PodVolumeContainer.js
  plugins/services/src/js/containers/volume-detail/PodVolumeDetail.js
  plugins/services/src/js/routes/services.js
  plugins/services/src/js/structs/Pod.js
  plugins/services/src/js/structs/PodSpec.js
  plugins/services/src/js/structs/Volume.js
  plugins/services/src/js/utils/MarathonUtil.js
Labels: high priority

#2857 Backport(1.11): update moment
  npm-shrinkwrap.json
  package.json
  src/js/structs/__tests__/JobRunList-test.js
  src/js/structs/__tests__/JobTaskList-test.js
  src/js/utils/DateUtil.js
Labels: high priority

#2851 fix(MesosStateStore): adjust stream data handling
  src/js/stores/MesosStateStore.js
Labels: blocker

#2858 [Backports 1.11] Fabs/1.11/fix/dcos 21784 mesos stream microtask
  src/js/stores/MesosStateStore.js
Labels: blocker

#2817 DCOS_OSS-1564: Let's update webpack (2nd try)
  .babelrc
  npm-shrinkwrap.json
  package.json
  plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
  postcss.config.js
  scripts/inline-bootstrap-css.js
  src/index.html
  src/js/config/Config.js
  src/js/index.js
  src/styles/components/application-preloader/styles.less
  webpack/plugins/svg-compiler-plugin.js
  webpack/proxy.template.js
  webpack/webpack.config.babel.js
  webpack/webpack.config.js
  webpack/webpack.dev.babel.js
  webpack/webpack.dev.js
  webpack/webpack.production.babel.js
  webpack/webpack.production.js
  webpack/webpack.test.js
Labels: data-layer

#2845 [BACKPORT] DCOS-21190: hide text if the service status is N/A on 1.11
  plugins/services/src/js/containers/services/ServicesTable.js
  plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
  plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap
Labels: high priority

#2861 [1.11] feat(package-describe): add fixture for x-region:string
  tests/_fixtures/cosmos/package-describe.json
Labels: blocker

#2840 DCOS-21640: Wrap cosmos repository API with http-service
  npm-shrinkwrap.json
  package.json
  plugins/catalog/src/js/repositories/__tests__/repositoriesStream-test.js
  plugins/catalog/src/js/repositories/repositoriesStream.js
  src/js/events/CosmosPackagesActions.js
  src/js/events/__tests__/CosmosPackagesActions-test.js
Labels: data-layer, high priority

#2853 fix(ServiceStorageConfigSection): adjust getDefinition default
  plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js
Labels: high priority
