Repository dcos/dcos-ui, pull requests merged in 2018-12, with the labels that each got.

#3441 DCOS-46053: Metronome client to stop sending Content-Type header with GET requests
  src/js/events/MetronomeClient.ts
  src/js/events/__tests__/MetronomeClient-test.ts
Labels: COPS

#3445 DCOS-43091: [COPS] Logs view / Nodes view don't scroll in Firefox
  src/styles/components/code/styles.less
  src/styles/components/code/variables.less
Labels: COPS

#3447 DCOS-46049: [1.12] COPS-3759 affecting dcos-ui: When no nodes are in the cluster the message should have different wording
  plugins/nodes/src/js/pages/NodesAgents.js
Labels: COPS, No Pressure

#3460 DCOS-46093 COPS-3907
  src/js/components/FrameworkConfigurationForm.js
  src/js/components/__tests__/FrameworkConfigurationForm-test.js
Labels: COPS

#3461 DCOS-46094 COPS-3907
  src/js/components/FrameworkConfigurationForm.js
  src/js/components/__tests__/FrameworkConfigurationForm-test.js
Labels: COPS

#3484 DCOS-46294 - COPS-4205: No tasks show for a service
  npm-shrinkwrap.json
  package.json
Labels: COPS

#3463 chore: upgrade cypress 3.1.3
  npm-shrinkwrap.json
  package.json
Labels: No Pressure

#3435 Auto update typescript with Renovate
  renovate.json
Labels: No Pressure
