Repository dcos/dcos-ui, pull requests merged in 2018-04, with the labels that each got.

#2852 DCOS-18691 typescript support
  npm-shrinkwrap.json
  package.json
  tsconfig.json
  tslint.json
  webpack/webpack.config.js
Labels: data-layer

#2841 DCOS-21752 DOCUMENTATION describes the mediator api
  packages/data-service/README.md
Labels: data-layer, high priority

#2873 DCOS-20260: Include id search in task text filter
  plugins/services/src/js/filters/TaskNameTextFilter.js
  plugins/services/src/js/filters/__tests__/TaskNameTextFilter-test.js
Labels: needs 1.11 PR

#2871 DCOS-21798: render empty modal if the service is not loaded
  plugins/services/src/js/components/modals/EditServiceModal.js
  plugins/services/src/js/components/modals/__tests__/EditServiceModal-test.js
Labels: blocker

#2879 DCOS_OSS-2206: Add enzyme to 1.11
  jest/setupTestFramework.js
  npm-shrinkwrap.json
  package.json
Labels: blocker

#2819 [Backport 1.10] - fix(labelsReducer): fix labels reducer to accept empty strings
  .babelrc
  jest/preprocessor.js
  npm-shrinkwrap.json
  package.json
  plugins/services/src/js/components/modals/CreateServiceModalForm.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Labels.js
  webpack/webpack.dev.babel.js
  webpack/webpack.test.js
Labels: high priority

#2878 DCOS-21981 [data-service package] Graphql Library
  npm-shrinkwrap.json
  package.json
  packages/data-service/.gitignore
  packages/data-service/LICENSE
  packages/data-service/package-lock.json
  packages/data-service/package.json
  packages/data-service/src/__tests__/graphqlObservable-test.js
  packages/data-service/src/graphqlObservable.js
  packages/data-service/src/index.js
  packages/data-service/src/recomposeRx.js
Labels: data-layer, high priority

#2864 DCOS-21639 Add graphql to the RepositoriesTab + data-service api
  plugins/catalog/src/js/repositories/RepositoriesTab.js
  plugins/catalog/src/js/repositories/RepositoriesTabUI.js
  plugins/catalog/src/js/repositories/__tests__/repositoriesStream-test.js
  plugins/catalog/src/js/repositories/repositoriesModel.js
  plugins/catalog/src/js/repositories/repositoriesStream.js
  src/js/events/CosmosPackagesActions.js
  src/js/events/__tests__/CosmosPackagesActions-test.js
  src/js/pages/system/RepositoriesTab.js
  src/js/routes/settings.js
Labels: data-layer, high priority

#2874 DCOS-21798 & DCOS-21614: Backport to 1.11
  plugins/services/src/js/components/HighOrderServiceConfiguration.js
  plugins/services/src/js/components/modals/EditServiceModal.js
  plugins/services/src/js/components/modals/__tests__/EditServiceModal-test.js
Labels: blocker

#2898 DCOS-22110: CI refactoring Day1 patch
  Dockerfile
  Jenkinsfile
  package.json
  scripts/ci/bump-version
  scripts/ci/release-latest
  scripts/ci/release-version
  scripts/ci/utils/create-bump-pr
  scripts/ci/utils/update-dcos-repo
  system-tests/driver-config/jenkins.sh
Labels: high priority

#2902 Add text filter in nodes
  plugins/nodes/src/js/filters/NodesTextFilter.js
  plugins/nodes/src/js/filters/__tests__/NodesTextFilter-test.js
  plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
Labels: blocker

#2890 fix(MesosStateStore): adjust stream event sampling
  src/js/stores/MesosStateStore.js
Labels: blocker

#2901 DCOS-22128 - fix(marathonUtil): fix parsePod function
  plugins/services/src/js/utils/MarathonUtil.js
Labels: blocker

#2908 fix(DSLInputField): adjust change event handling
  src/js/components/DSLInputField.js
Labels: high priority

#2903 fix(OverviewDetailTab): display mesos start and elected time
  src/js/pages/system/OverviewDetailTab.js
  tests/_fixtures/v1/get_flags.json
  tests/_fixtures/v1/get_master.json
  tests/_fixtures/v1/get_version.json
  tests/_support/index.js
  tests/pages/system/overview/ClusterDetails-cy.js
Labels: blocker

#2888 fix(MesosStateStore): adjust stream data handling
  src/js/stores/MesosStateStore.js
Labels: blocker

#2911 fix(DSLInputField): adjust change event handling
  src/js/components/DSLInputField.js
Labels: high priority

#2915 DCOS_OSS-2397: shows filter default on task page loading
  plugins/services/src/js/containers/tasks/TasksContainer.js
  plugins/services/src/js/containers/tasks/__tests__/TasksContainer-test.js
Labels: blocker

#2918 fix(MesosStateStore): add linearBackoff retry to the stream
  CONTRIBUTING.md
  npm-shrinkwrap.json
  package.json
  src/js/stores/MesosStateStore.js
  src/js/utils/__tests__/rxjsUtils-test.js
  src/js/utils/rxjsUtils.js
Labels: blocker

#2917 [Backport 1.11] DCOS_OSS-2398: shows filter default on task page loading
  plugins/services/src/js/containers/tasks/TasksContainer.js
  plugins/services/src/js/containers/tasks/__tests__/TasksContainer-test.js
Labels: blocker

#2922 [1.11] chore(*): bump mesos-client and http-service
  npm-shrinkwrap.json
  package.json
Labels: blocker

#2923 ↩️ fix(MesosStateStore): adjust stream event sampling
  src/js/stores/MesosStateStore.js
Labels: blocker

#2924 ↩️ fix(MesosStateStore): adjust stream data handling
  src/js/stores/MesosStateStore.js
Labels: blocker

#2919 fix(MesosStream): delay reconnections
  src/js/core/MesosStream.js
Labels: high priority
