Repository dcos/dcos-ui, pull requests merged in 2018-07, with the labels that each got.

#3042 DCOS-38492 delete job menu refactor
  plugins/jobs/src/js/JobDelete.js
  plugins/jobs/src/js/components/JobDeleteModal.js
  plugins/jobs/src/js/jobsDelete.js
  plugins/jobs/src/js/jobsMenu.js
  plugins/jobs/src/js/pages/JobDetailPage.js
  src/js/pages/jobs/JobDetailPage.js
  src/js/pages/jobs/JobDetailPageContainer.js
Labels: data-layer

#3050 DCOS-38892: fix job schedulestatus resolver
  plugins/jobs/src/js/types/Job.ts
Labels: blocker

#3059 DCOS-39106: Show allocated resources for frameworks
  plugins/services/src/js/containers/services/ServicesContainer.js
  plugins/services/src/js/structs/Framework.js
  plugins/services/src/js/structs/__tests__/Framework-test.js
  src/js/stores/DCOSStore.js
  src/js/stores/__tests__/DCOSStore-test.js
Labels: blocker

#3092 fix(ServiceDebugContainer): stop using deprecated label
  plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
Labels: COPS

#3106 fix(serviceForm): fix environment variable reducer
  plugins/services/src/js/components/modals/CreateServiceModalForm.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerEnvironmentVariables.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js
Labels: hold merge

#3125 fix(index): fix typo in removeEventListener function name
  src/js/pages/Index.js
Labels: blocker
