Repository dcos/dcos-ui, pull requests merged in 2018-02, with the labels that each got.

#2726 fix(taskDSLFilters): set default value for dsl Filters
  plugins/services/src/js/containers/tasks/TasksContainer.js
Labels: blocker

#2711 DCOS-20976: fix(CliInstall): renames terminal to command prompt
  src/js/components/modals/CliInstallModal.js
Labels: high priority

#2733 Drozhkov/dcos 21044 fix sdk tasks health
  src/js/stores/MesosStateStore.js
  src/js/stores/__tests__/MesosStateStore-test.js
  src/js/utils/MesosStateUtil.js
  src/js/utils/__tests__/MesosStateUtil-test.js
Labels: blocker, needs 1.11 PR

#2730 [backport 1.11] fix(UniversePackage): fallback to type: "object" for config
  src/js/structs/UniversePackage.js
  src/js/structs/__tests__/UniversePackage-test.js
Labels: blocker

#2746 fix(raml-scripts): updates the download link for the raml files
  scripts/pre-install
  scripts/utils/marathon
Labels: high priority, needs 1.11 PR

#2749 1.11 / fix(raml-scripts): updates the download link for the raml files
  scripts/pre-install
  scripts/utils/marathon
Labels: blocker

#2728 fix(taskDSLFilters): set default value for dsl Filters
  plugins/services/src/js/containers/tasks/TasksContainer.js
Labels: blocker

#2747 fix(MesosStateStore): flag all SDK tasks
  src/js/stores/MesosStateStore.js
  src/js/stores/__tests__/MesosStateStore-test.js
  src/js/utils/MesosStateUtil.js
  src/js/utils/__tests__/MesosStateUtil-test.js
Labels: blocker

#2738 DCOS-20309 Empty state for catalog
  src/js/pages/catalog/PackagesTab.js
  src/js/pages/catalog/__tests__/PackagesTab-test.js
  src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap
Labels: blocker

#2752 DCOS-21135: display mesos start and elected time
  src/js/pages/system/OverviewDetailTab.js
  tests/_fixtures/v1/get_flags.json
  tests/_fixtures/v1/get_master.json
  tests/_fixtures/v1/get_version.json
  tests/_support/index.js
  tests/pages/system/overview/ClusterDetails.js
Labels: blocker, needs 1.11 PR, pass

#2732 [backport 1.11] feat(FrameworkConfiguration): open to form when deploying
  plugins/services/src/js/pages/EditFrameworkConfiguration.js
  src/js/components/FrameworkConfiguration.js
  system-tests/universe/test-universe.js
  tests/pages/catalog/packages/package/PackageTab-cy.js
Labels: high priority

#2698 feat(FrameworkConfiguration): open to form when deploying
  plugins/services/src/js/pages/EditFrameworkConfiguration.js
  src/js/components/FrameworkConfiguration.js
  system-tests/universe/test-universe.js
  tests/pages/catalog/packages/package/PackageTab-cy.js
Labels: high priority

#2735 feat(PodEndpoints): Add vip input to virtual networks
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/Endpoints.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Containers-test.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Endpoints-test.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: blocker, pass

#2736 DCOS-20948: keep unknown network attributes
  plugins/services/src/js/reducers/serviceForm/FormReducers/Networks.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Networks.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Networks-test.js
Labels: high priority

#2754 fix(Endpoints): remove spaces from the comma delimited list of endpoints
  plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
  plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
  plugins/services/src/js/structs/ServiceEndpoint.js
  plugins/services/src/js/structs/__tests__/ServiceEndpoint-test.js
Labels: high priority, needs 1.11 PR

#2756 [1.11 Backport] DCOS-21304: Remove spaces from endpoints list
  plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
  plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
  plugins/services/src/js/structs/ServiceEndpoint.js
  plugins/services/src/js/structs/__tests__/ServiceEndpoint-test.js
Labels: high priority

#2748 Master: DCOS-21229: fix(TaskTable): fix sorting in tables
  plugins/services/src/js/containers/tasks/TaskTable.js
  plugins/services/src/js/utils/TaskTableUtil.js
  tests/_fixtures/marathon-1-task/mesos-subscribe.js
  tests/_fixtures/marathon-1-task/summary.json
  tests/_fixtures/marathon-pods/groups.json
  tests/pages/nodes/NodesPage-cy.js
  tests/pages/services/TasksTable-cy.js
Labels: blocker

#2745 Backport: DCOS-20976
  src/js/components/modals/CliInstallModal.js
Labels: high priority

#2737 1.11: DCOS-21229: fix sorting in tables
  plugins/services/src/js/containers/tasks/TaskTable.js
  plugins/services/src/js/utils/TaskTableUtil.js
  tests/_fixtures/marathon-1-task/mesos-subscribe.js
  tests/_fixtures/marathon-1-task/summary.json
  tests/_fixtures/marathon-pods/groups.json
  tests/pages/nodes/NodesPage-cy.js
  tests/pages/services/TasksTable-cy.js
Labels: blocker

#2734 [1.11 Backport] feat(PodEndpoints): Add vip input to virtual networks
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/Endpoints.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Containers-test.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Endpoints-test.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: blocker

#2764 DCOS-21229: Sorting in pods table
  plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
  plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
  tests/_fixtures/marathon-1-pod-group/groups.json
  tests/_fixtures/marathon-1-pod-group/summary.json
  tests/_support/index.js
  tests/pages/services/PodDetail-cy.js
Labels: blocker, needs 1.11 PR

#2769 Backport 1.11: DCOS-21229: Sort pods with zones & regions
  plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
  plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
  tests/_fixtures/marathon-1-pod-group/groups.json
  tests/_fixtures/marathon-1-pod-group/summary.json
  tests/_support/index.js
  tests/pages/services/PodDetail-cy.js
Labels: blocker

#2758 [Backport 1.11] fix(PodStorageConfigSection): fix variable reference
  plugins/services/src/js/service-configuration/PodStorageConfigSection.js
  tests/pages/services/ServicePodReviewScreen-cy.js
Labels: high priority

#2757 fix(PodStorageConfigSection): fix variable reference
  plugins/services/src/js/service-configuration/PodStorageConfigSection.js
  tests/pages/services/ServicePodReviewScreen-cy.js
Labels: high priority

#2772 [Backport:1.11] DCOS-21122: fix(ServiceForm): fixes focus/change/blur behaviour
  plugins/services/src/js/components/modals/CreateServiceModalForm.js
  tests/pages/services/ServiceFormModal-cy.js
  tests/pages/services/ServicePodReviewScreen-cy.js
  tests/pages/services/ServiceReviewScreen-cy.js
Labels: high priority

#2681 feat(EmptyStates): consolidate config value empty states
  plugins/services/src/js/components/ConfigurationMapBooleanValue.js
  plugins/services/src/js/components/ConfigurationMapDurationValue.js
  plugins/services/src/js/components/ConfigurationMapMultilineValue.js
  plugins/services/src/js/components/ConfigurationMapSizeValue.js
  plugins/services/src/js/components/ConfigurationMapTable.js
  plugins/services/src/js/components/ConfigurationMapValueWithDefault.js
  plugins/services/src/js/components/__tests__/ConfigurationMapTable-test.js
  plugins/services/src/js/containers/services/ServicesTable.js
  plugins/services/src/js/service-configuration/PodGeneralConfigSection.js
  plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js
  plugins/services/src/js/utils/ServiceConfigDisplayUtil.js
  src/js/components/FrameworkConfigurationReviewScreen.js
  src/js/constants/EmptyStates.js
  tests/pages/services/ServiceExternalVolumes-cy.js
  tests/pages/services/ServicePodReviewScreen-cy.js
  tests/pages/services/ServiceReviewScreen-cy.js
Labels: pass

#2776 [Regression] fix(integrationTests): fixes empty state of tests
  tests/pages/services/ServicePodReviewScreen-cy.js
Labels: blocker

#2781 fix(struct/Node): does not throw exception when resources are empty
  src/js/structs/Node.js
  src/js/structs/__tests__/Node-test.js
Labels: high priority

#2777 DCOS-21359: fix(ServicesContainer): checks and updates modalProps if needed
  plugins/services/src/js/containers/services/ServicesContainer.js
  plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js
Labels: blocker

#2793 chore(reactjs-components): update package to 0.20.3
  npm-shrinkwrap.json
  package.json
Labels: high priority

#2788 [Backport 1.11] DCOS-21359: fix(ServicesContainer): checks and updates modalProps if needed
  plugins/services/src/js/containers/services/ServicesContainer.js
  plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js
Labels: blocker

#2782 Fabs/1.11/fix/dcos 21361 nodes resource failure backports
  src/js/structs/Node.js
  src/js/structs/__tests__/Node-test.js
Labels: high priority

#2794 [1.11] update package to 0.20.3 DCOS-21362
  npm-shrinkwrap.json
  package.json
Labels: high priority
