Repository dcos/dcos-ui, pull requests merged in 2019-05, with the labels that each got.

#3820 DCOS-51269: COPS-4710 affecting : Package-specific icons not showing for some services installed from Universe
  plugins/services/src/js/stores/MarathonStore.js
  plugins/services/src/js/structs/Application.js
  plugins/services/src/js/structs/__tests__/Application-test.js
Labels: COPS, ready to review

#3864 DCOS-52749 allow to route packages without a version
  src/js/events/CosmosPackagesActions.js
  src/js/pages/catalog/PackageDetailTab.js
Labels: ready to review

#3852 DCOS-52783: Require password confirmation when creating new user
  locale/en/messages.json
  locale/zh/messages.json
  src/js/components/modals/UserFormModal.js
Labels: ready to review

#3825 DCOS-51824: In Service Create/Edit form, expand the advanced settings if they contain errors
  plugins/services/src/js/components/forms/GeneralServiceFormSection.js
  plugins/services/src/js/components/modals/CreateServiceModal.js
  plugins/services/src/js/components/modals/CreateServiceModalForm.js
  src/js/components/form/AdvancedSection.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: ready to review

#3876 [1.13] COPS-4710 affecting : Package-specific icons not showing for some services installed from Universe
  plugins/services/src/js/stores/MarathonStore.js
  plugins/services/src/js/structs/Application.js
  plugins/services/src/js/structs/__tests__/Application-test.js
Labels: COPS

#3880 [spike] DCOS-53725 Disable tracking in the Config
  src/js/config/Config.template.ts
Labels: No Pressure

#3874 [spike] DCOS-21195
  src/styles/components/secret-value/styles.less
Labels: No Pressure

#3850 Add types for marathon
  src/js/types/marathon.ts
Labels: No Pressure

#3899 fix: preserve concurrencyPolicy and scheduleId in job json
  src/js/utils/JobUtil.js
  src/js/utils/__tests__/JobUtil-test.js
Labels: COPS

#3875 [1.12] COPS-4710 affecting : Package-specific icons not showing for some services installed from Universe
  plugins/services/src/js/stores/MarathonStore.js
  plugins/services/src/js/structs/Application.js
  plugins/services/src/js/structs/__tests__/Application-test.js
Labels: COPS
