Repository dcos/dcos-ui, pull requests merged in 2019-06, with the labels that each got.

#3920 DCOS-43777: provide default volume type for DSS volumes
  plugins/services/src/js/components/modals/CreateServiceModal.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js
  plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
  plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
  plugins/services/src/js/validators/MarathonAppValidators.js
  plugins/services/src/js/validators/MarathonPodValidators.js
  plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
  plugins/services/src/js/validators/__tests__/MarathonPodValidators-test.js
Labels: ready to review

#3763 [spike] DCOS-51050: Services: Reappearing error before the configuration is submitted
  plugins/services/src/js/pages/EditFrameworkConfiguration.js
  src/js/components/FrameworkConfiguration.js
  src/js/pages/catalog/DeployFrameworkConfiguration.js
Labels: No Pressure

#3902 [spike] DCOS-52108: JSON erros in service creation are not being reset
  plugins/services/src/js/components/modals/CreateServiceModal.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: No Pressure

#3922 DCOS-43777: provide default volume type for DSS volumes
  plugins/services/src/js/components/modals/CreateServiceModal.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
  plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js
  plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
  plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
  plugins/services/src/js/validators/MarathonAppValidators.js
  plugins/services/src/js/validators/MarathonPodValidators.js
  plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
  plugins/services/src/js/validators/__tests__/MarathonPodValidators-test.js
Labels: ready to review

#3925 DCOS-48532: No text button in Marathon configuration
  src/styles/components/framework-configuration/styles.less
Labels: work in progress

#3904 DCOS-43588: UI doesn't reflect executor's resources for Pods on the Services page
  plugins/services/src/js/structs/Service.js
  plugins/services/src/js/structs/__tests__/Service-test.js
Labels: Bug Fix

#3936 DCOS-49181: Version column in service table shows misleading information
  plugins/services/src/js/columns/ServicesTableVersionColumn.tsx
  plugins/services/src/js/containers/services/ServicesTable.js
  plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
  plugins/services/src/js/utils/Version.ts
  plugins/services/src/js/utils/__tests__/Version-test.ts
  tests/_fixtures/marathon-1-task/groups-sdk-services.json
  tests/pages/services/ServiceTable-cy.js
Labels: Bug Fix

#3935 DCOS-48718: i18n exhibition error for task list of UI in Chinese
  locale/zh/messages.json
Labels: Bug Fix

#3930 DCOS_OSS-1766: Service config page mislabels host ports in dcos-ui
  plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
  tests/pages/services/ServiceReviewScreen-cy.js
Labels: Bug Fix

#3938 DCOS-50657: SDK Plans - 404 errors in console until scheduler exists
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/SDKPlans.tsx
  src/styles/components/service-endpoints/styles.less
Labels: Bug Fix

#3888 [spike] DCOS-21504: Switching from Service to Pod breaks the Networking tab
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/components/modals/CreateServiceModalForm.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: Bug Fix

#3903 [spike] DCOS-40571: Filter by Type on the Nodes Agents view (both on list and grid view)
  plugins/nodes/src/js/components/dsl/NodesTypeDSLSection.js
  plugins/nodes/src/js/filters/NodesTypeFilter.js
  plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
  tests/pages/nodes/NodesPage-cy.js
Labels: No Pressure

#3897 [spike] DCOS-49324: Service group creation rejects names that should be valid
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/modals/ServiceGroupFormModal.js
  plugins/services/src/js/utils/ServiceValidatorUtil.js
  tests/pages/services/ServiceTable-cy.js
Labels: Bug Fix

#3900 [spike] DCOS-39292: Edit Jobs: Make ID field non - editable
  plugins/jobs/src/js/components/JobsForm.tsx
  plugins/jobs/src/js/components/JobsFormModal.tsx
  plugins/jobs/src/js/components/form/GeneralFormSection.tsx
  tests/pages/jobs/JobActions-cy.js
Labels: Bug Fix

#3928 DCOS-43896: Progress indicator doesn't go away without a page reload
  plugins/services/src/js/components/ServiceBreadcrumbs.js
  plugins/services/src/js/containers/service-detail/ServiceDetail.js
  src/js/components/Breadcrumb.js
Labels: Bug Fix

#3953 DCOS-45226: fix(jobsform): fix jobs form to preserve docker params
  src/js/utils/JobUtil.js
  src/js/utils/__tests__/JobUtil-test.js
Labels: Bug Fix

#3808 [spike] DCOS-46215: Error requesting UI Configuration message email is shown as {0}
  locale/en/messages.json
  locale/zh/messages.json
  src/js/components/RequestErrorMsg.js
Labels: Bug Fix

#3944 DCOS-11171: Incorrect service id from the task name extraction ServiceUtil.getServiceNameFromTaskID
  plugins/services/src/js/utils/ServiceUtil.js
Labels: Bug Fix

#3945 DCOS-47643: Error: Expected an array.
  plugins/services/src/js/stores/MarathonStore.js
  plugins/services/src/js/stores/__tests__/MarathonStore-test.js
Labels: Bug Fix

#3957 DCOS-48972: TypeError: Cannot read property 'description' of null
  plugins/catalog/src/js/repositories/RepositoriesAdd.js
Labels: Bug Fix
