Repository dcos/dcos-ui, pull requests merged in 2019-03, with the labels that each got.

#3602 [spike] DCOS-48028: [1.12] Metronome JOBs show "Invalid Date".
  plugins/jobs/src/js/components/JobsOverviewTable.js
  src/js/utils/DateUtil.js
  src/js/utils/__tests__/DateUtil-test.js
Labels: No Pressure

#3659 update typescript to 3.3.3333
  package-lock.json
  package.json
Labels: ready to review

#3662 [spike] delete .nvmrc
  .nvmrc
Labels: No Pressure, ready to review

#3672 update renovate config
  renovate.json
Labels: No Pressure, ready to review

#3676 fix(deps): update dependency @dcos/ui-kit to v1.35.0
  package-lock.json
  package.json
Labels: renovate

#3674 chore(deps): update babel6 monorepo
  package-lock.json
  package.json
Labels: renovate

#3686 chore(deps): update dependency @semantic-release/exec to v3.3.2
  package-lock.json
  package.json
Labels: renovate

#3675 chore(deps): update dependency babel-plugin-macros to v2.5.0
  package-lock.json
  package.json
Labels: renovate

#3684 chore(deps): update dependency @commitlint/cli to v6.2.0
  package-lock.json
  package.json
Labels: renovate

#3688 chore(deps): pin dependencies
  packages/foundation-ui/package.json
Labels: renovate

#3692 chore(deps): update dependency @types/lodash.isequal to v4.5.5
  package-lock.json
  package.json
Labels: renovate

#3691 chore(deps): update dependency @types/lingui__react to v2.5.2
  package-lock.json
  package.json
Labels: renovate

#3689 chore(deps): update dependency @types/react to v16.8.8
  package-lock.json
  package.json
Labels: renovate

#3687 chore(deps): update dependency @sentry/cli to v1.40.0
  package-lock.json
  package.json
Labels: renovate

#3678 fix(deps): update dependency clipboard to v1.7.1
  package-lock.json
  package.json
Labels: renovate

#3677 fix(deps): update dependency browser-info to v0.5.0
  package-lock.json
  package.json
Labels: renovate

#3693 chore(deps): update dependency @types/react-router to v2.0.56
  package-lock.json
  package.json
Labels: renovate

#3696 chore(deps): update dependency babel-loader to v7.1.5
  package-lock.json
  package.json
Labels: renovate

#3699 fix the ee-build
  package-lock.json
  package.json
Labels: ready to review

#3694 chore(deps): update dependency @types/recompose to v0.30.5
  package-lock.json
  package.json
Labels: renovate

#3705 chore(deps): update dependency cypress to v3.2.0
  package-lock.json
  package.json
Labels: renovate

#3708 chore(deps): update dependency eslint to v3.19.0
  package-lock.json
  package.json
Labels: renovate

#3668 chore: remove string-replace-webpack-plugin
  package-lock.json
  package.json
Labels: No Pressure, ready to review

#3670 chore: remove webpack-notifier
  package-lock.json
  package.json
Labels: No Pressure, ready to review

#3669 chore: remove source-map-loader
  package-lock.json
  package.json
Labels: No Pressure, ready to review

#3664 chore: remove obsolete font-files
  src/fonts/source-sans-pro/OFL.txt
  src/fonts/source-sans-pro/SourceSansPro-Black.ttf
  src/fonts/source-sans-pro/SourceSansPro-Black.woff
  src/fonts/source-sans-pro/SourceSansPro-BlackItalic.ttf
  src/fonts/source-sans-pro/SourceSansPro-BlackItalic.woff
  src/fonts/source-sans-pro/SourceSansPro-Bold.ttf
  src/fonts/source-sans-pro/SourceSansPro-Bold.woff
  src/fonts/source-sans-pro/SourceSansPro-BoldItalic.ttf
  src/fonts/source-sans-pro/SourceSansPro-BoldItalic.woff
  src/fonts/source-sans-pro/SourceSansPro-ExtraLight.ttf
  src/fonts/source-sans-pro/SourceSansPro-ExtraLight.woff
  src/fonts/source-sans-pro/SourceSansPro-ExtraLightItalic.ttf
  src/fonts/source-sans-pro/SourceSansPro-ExtraLightItalic.woff
  src/fonts/source-sans-pro/SourceSansPro-Italic.ttf
  src/fonts/source-sans-pro/SourceSansPro-Italic.woff
  src/fonts/source-sans-pro/SourceSansPro-Light.ttf
  src/fonts/source-sans-pro/SourceSansPro-Light.woff
  src/fonts/source-sans-pro/SourceSansPro-LightItalic.ttf
  src/fonts/source-sans-pro/SourceSansPro-LightItalic.woff
  src/fonts/source-sans-pro/SourceSansPro-Regular.ttf
  src/fonts/source-sans-pro/SourceSansPro-Regular.woff
  src/fonts/source-sans-pro/SourceSansPro-Semibold.ttf
  src/fonts/source-sans-pro/SourceSansPro-Semibold.woff
  src/fonts/source-sans-pro/SourceSansPro-SemiboldItalic.ttf
  src/fonts/source-sans-pro/SourceSansPro-SemiboldItalic.woff
  webpack/webpack.config.js
Labels: No Pressure, ready to review

#3663 remove an obsolete RAML
  api/component-health/component-health-api-spec.raml
Labels: No Pressure, ready to review

#3695 chore(deps): update dependency autoprefixer to v6.7.7
  package-lock.json
  package.json
Labels: renovate

#3697 chore(deps): update dependency colors to v1.3.3
  package-lock.json
  package.json
Labels: renovate

#3701 chore(deps): update dependency console to v0.7.2
  package-lock.json
  package.json
Labels: renovate

#3667 chore: remove an obsolete library
  package-lock.json
  package.json
  src/js/stores/__tests__/DCOSStore-test.js
  src/js/utils/__tests__/ApplicationUtil-test.js
Labels: No Pressure, ready to review

#3706 chore(deps): update dependency enzyme to v3.9.0
  package-lock.json
  package.json
  src/js/components/__tests__/TabButton-test.js
  src/js/components/modals/__tests__/__snapshots__/LanguagePreferenceFormModal-test.js.snap
Labels: renovate

#3707 chore(deps): update dependency enzyme-adapter-react-16 to v1.11.2
  package-lock.json
  package.json
  src/js/components/modals/__tests__/__snapshots__/LanguagePreferenceFormModal-test.js.snap
Labels: renovate

#3666 chore: remove obsolete webpack-plugin optimize-css-assets-webpack-plugin
  package-lock.json
  package.json
Labels: No Pressure, ready to review

#3711 chore(deps): update dependency eslint-plugin-import to v1.16.0
  package-lock.json
  package.json
Labels: renovate

#3713 chore(deps): update dependency eslint-plugin-prettier to v2.7.0
  package-lock.json
  package.json
Labels: renovate

#3715 chore(deps): update dependency file-loader to v1.1.11
  package-lock.json
  package.json
Labels: renovate

#3716 chore(deps): update dependency glob to v7.1.3
  package-lock.json
  package.json
Labels: renovate

#3717 chore(deps): update dependency jasmine-reporters to v2.3.2
  package-lock.json
  package.json
Labels: renovate

#3721 chore(deps): update dependency less to v2.7.3
  package-lock.json
  package.json
Labels: renovate

#3724 chore(deps): update dependency localstorage to v1.0.4
  package-lock.json
  package.json
Labels: renovate

#3712 chore(deps): update dependency eslint-plugin-jsx-a11y to v2.2.3
  package-lock.json
  package.json
Labels: renovate

#3714 chore(deps): update dependency eslint-plugin-react to v6.10.3
  package-lock.json
  package.json
Labels: renovate

#3726 chore(deps): update dependency marked to v0.6.1
  package-lock.json
  package.json
  src/js/utils/__tests__/StringUtil-test.js
Labels: renovate

#3728 chore(deps): update dependency mini-css-extract-plugin to v0.5.0
  package-lock.json
  package.json
Labels: renovate

#3731 chore(deps): update dependency prettier to v1.16.4
  package-lock.json
  package.json
  plugins/jobs/src/js/components/JobsForm.tsx
  plugins/jobs/src/js/components/JobsFormModal.tsx
  plugins/jobs/src/js/components/form/ContainerFormSection.tsx
  plugins/jobs/src/js/components/form/ScheduleFormSection.tsx
  plugins/jobs/src/js/components/form/helpers/MetronomeJobValidators.ts
  plugins/jobs/src/js/components/form/reducers/JsonReducers.ts
Labels: renovate

#3740 chore(deps): update dependency typescript to v3.3.4000
  package-lock.json
  package.json
Labels: renovate

#3741 chore(deps): update graphql
  package-lock.json
  package.json
Labels: renovate
