Repository dcos/dcos-ui, pull requests merged in 2019-04, with the labels that each got.

#3762 [spike] DCOS-48838: Correct login screen for DC/OS Enterprise
  locale/en/messages.json
  locale/zh/messages.json
Labels: No Pressure

#3749 chore(deps): update lingui monorepo to v2.7.4
  package-lock.json
  package.json
Labels: renovate

#3575 [spike] DCOS-46215: Error requesting UI Configuration message email is shown as {0}
  locale/en/messages.json
  locale/zh/messages.json
  src/js/components/RequestErrorMsg.js
Labels: No Pressure

#3814 [Spike] DCOS-51672: camelcase svg attributes
  src/js/components/charts/TimeSeriesArea.js
Labels: No Pressure

#3807 DCOS-52771 - update service status codes
  plugins/services/src/js/constants/ServiceStatus.ts
  tests/_fixtures/marathon-pods/groups.js
Labels: ready to review

#3815 [Spike] DCOS-51627: make Container Image the default choice
  plugins/jobs/src/js/components/form/GeneralFormSection.tsx
  plugins/jobs/src/js/components/form/helpers/DefaultFormData.ts
  system-tests/jobs/test-jobs-cy.js
  tests/pages/jobs/JobJSONEditor-cy.js
Labels: No Pressure

#3813 [Spike] DCOS-51565: use default styling for disabled banner
  plugins/jobs/src/js/components/form/ContainerFormSection.tsx
  plugins/jobs/src/js/components/form/ScheduleFormSection.tsx
Labels: No Pressure
