Repository dcos/dcos-ui, pull requests merged in 2019-02, with the labels that each got.

#3588 add instructions for setting up private-plugins
  README.md
Labels: ready to review

#3593 Fix react@16 ref related bugs in reactjs-components
  package-lock.json
  package.json
Labels: blocker

#3579 DCOS-44840: feature public ip add network nodes endpoint client
  plugins/nodes/src/js/data/NodesNetworkClient.ts
  plugins/nodes/src/js/data/__tests__/NodesNetworkClient-test.ts
Labels: ready to review

#3497 [spike] DCOS-15019: Poor default for container Image
  plugins/services/src/js/components/forms/GeneralServiceFormSection.js
  plugins/services/src/js/constants/DefaultApp.js
  tests/pages/services/ServiceFormModal-cy.js
  tests/pages/services/ServiceReviewScreen-cy.js
Labels: No Pressure

#3573 [spike] DCOS-48015: [1.13] Adding Package Repository with priority 0, does not push all packages 1 priority down
  plugins/catalog/src/js/repositories/RepositoriesAdd.js
  plugins/catalog/src/js/repositories/data/repositoriesModel.js
  src/js/structs/RepositoryList.js
Labels: No Pressure

#3581 DCOS-47965 UI-Update Service client & data-layer
  packages/dcos-ui-update-client/LICENSE
  packages/dcos-ui-update-client/index.ts
  packages/dcos-ui-update-client/package.json
  packages/dcos-ui-update-client/src/DCOSUIUpdateClient.ts
  packages/dcos-ui-update-client/src/__tests__/DCOSUIUpdateClient-test.ts
  packages/dcos-ui-update-client/src/utils.ts
  src/js/data/ui-update/UIMetadata.ts
  src/js/data/ui-update/__tests__/index-test.ts
  src/js/data/ui-update/index.ts
Labels: ready to review

#3495 [spike] DCOS-46183 ${} inside Trans element
  locale/en/messages.json
  locale/zh/messages.json
  plugins/jobs/src/js/pages/JobConfiguration.js
Labels: No Pressure, hold merge

#3607 fix: ClickToSelect.js ref
  src/js/components/ClickToSelect.js
Labels: blocker

#3586 DCOS-44841: add network node resolver
  plugins/nodes/src/js/data/NodesNetworkClient.ts
  plugins/nodes/src/js/data/NodesResolver.ts
  plugins/nodes/src/js/data/__tests__/NodesResolver-test.ts
Labels: ready to review

#3601 [spike] DCOS-48014: [1.12] Adding Package Repository with priority 0, does not push all packages 1 priority down
  plugins/catalog/src/js/repositories/RepositoriesAdd.js
  plugins/catalog/src/js/repositories/data/repositoriesModel.js
  src/js/structs/RepositoryList.js
Labels: No Pressure

#3624 DCOS-49072: [1.12] The nodes tab, masters sub tab shows mesos version but does not label it as mesos
  plugins/nodes/src/js/components/LeaderGrid.js
  plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
  plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap
  src/js/translations/en-US.json
Labels: hold merge

#3598 DCOS-48262 Manual update/reset UX
  locale/en/messages.json
  locale/zh/messages.json
  package-lock.json
  package.json
  plugins/index.js
  plugins/ui-update/SDK.js
  plugins/ui-update/__tests__/queries-test.ts
  plugins/ui-update/commands.ts
  plugins/ui-update/components/AvailableUpdateRow.tsx
  plugins/ui-update/components/FallbackScreen.tsx
  plugins/ui-update/components/InitialScreen.tsx
  plugins/ui-update/components/InstalledVersion.tsx
  plugins/ui-update/components/UIDetails.tsx
  plugins/ui-update/hooks.js
  plugins/ui-update/index.js
  plugins/ui-update/queries.ts
  plugins/ui-update/types/FormattedPackageVersion.ts
  plugins/ui-update/types/UIAction.ts
  plugins/ui-update/utils/__tests__/index-test.ts
  plugins/ui-update/utils/index.ts
  src/js/components/ConfigurationMap.js
  src/js/components/ConfigurationMap.tsx
  src/js/components/ConfigurationMapLabel.tsx
  src/js/components/ConfigurationMapRow.js
  src/js/components/ConfigurationMapRow.tsx
  src/js/components/ConfigurationMapSection.js
  src/js/components/ConfigurationMapSection.tsx
  src/js/components/ConfigurationMapValue.js
  src/js/components/ConfigurationMapValue.tsx
  src/js/data/ui-update/UIMetadata.ts
  src/js/pages/settings/UISettingsPage.js
  tests/_fixtures/config/ui-update-enabled.json
  tests/_fixtures/ui-settings/default-version.json
  tests/_fixtures/ui-settings/package-versions-none.json
  tests/_fixtures/ui-settings/package-versions.json
  tests/_fixtures/ui-settings/version-010.json
  tests/_fixtures/ui-settings/version-011.json
  tests/_support/index.js
  tests/pages/system/settings/UISettings-cy.js
Labels: ready to review
