Repository dcos/dcos-ui, pull requests merged in 2019-07, with the labels that each got.

#3940 DCOS-21186: Service status panel on dashboard should sort by severity
  src/js/pages/DashboardPage.js
Labels: Bug Fix

#3956 DCOS-50023: Fail to display error coming from the service resume action
  plugins/services/src/js/components/modals/ServiceResumeModal.js
Labels: Bug Fix

#3959 DCOS_OSS-867: Unspecific GUI Error Message
  locale/en/messages.json
  locale/zh/messages.json
  src/js/components/CosmosErrorMessage.js
  tests/pages/catalog/packages/PackagesTab-cy.js
Labels: Bug Fix

#3952 DCOS-50792: TypeError: Cannot read property 'jsonValue' of null
  src/js/components/JSONEditor.js
  src/js/components/__tests__/JSONEditor-test.js
Labels: Bug Fix

#3955 DCOS-50259: Possible exception in the Services Form Constraints reducer
  plugins/services/src/js/reducers/serviceForm/FormReducers/Constraints.js
  plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Constraints-test.js
Labels: Bug Fix

#3901 [spike] DCOS_OSS-2207: Endpoints tab for pods doesn't show container port
  plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
  plugins/services/src/js/containers/service-connection/__tests__/ServicePodConnectionEndpointList-test.js
  tests/_fixtures/marathon-1-pod-group/groups.json
  tests/pages/services/PodDetail-cy.js
Labels: Bug Fix

#3811 chore(deps): update dependency @sentry/cli to v1.46.0
  package-lock.json
  package.json
Labels: renovate

#3444 [spike] DCOS_OSS-401: Incorrect error message for priority when adding a new repo
  plugins/catalog/src/js/repositories/components/AddRepositoryFormModal.js
Labels: Bug Fix

#3978 DCOS-56244: Networks empty IP subnet
  src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js
Labels: Bug Fix

#3187 DCOS-14972: Enable dot separated values in Cypress tests
  system-tests/jobs/test-jobs-cy.js
  system-tests/services/test-apps-cy.js
  system-tests/services/test-pods-cy.js
  tests/pages/jobs/JobJSONEditor-cy.js
  tests/pages/services/ServicePodReviewScreen-cy.js
  tests/pages/services/ServiceReviewScreen-cy.js
Labels: No Pressure, work in progress

#3983 chore(deps): update dependency @types/lingui__macro to v2.7.3
  package-lock.json
  package.json
Labels: renovate

#3993 chore(deps): update dependency @types/recompose to v0.30.6
  package-lock.json
  package.json
Labels: renovate

#3574 [spike] DCOS-20182: Error Validation in Delete Modal
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/modals/ServiceDestroyModal.js
  plugins/services/src/js/containers/services/ServicesContainer.js
Labels: No Pressure
