Repository dcos/dcos-ui, pull requests merged in 2019-08, with the labels that each got.

#3750 chore(deps): update react
  package-lock.json
  package.json
Labels: renovate

#4019 chore(deps): update react
  package-lock.json
  package.json
Labels: renovate

#4020 DCOS-57287: User create modal does not clear password errors on close
  src/js/components/modals/UserFormModal.js
Labels: Bug Fix

#4021 chore(deps): update dependency @sentry/cli to v1.47.1
  package-lock.json
  package.json
Labels: renovate

#3943 DCOS-41310, DCOS-41842, DCOS-42506
  plugins/nodes/src/js/pages/NodesAgents.js
  plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
  plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js
  plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
  plugins/services/src/js/components/FilterByFramework.js
  tests/pages/nodes/NodesPage-cy.js
Labels: Bug Fix

#4023 chore(deps): update dependency glob to v7.1.4
  package-lock.json
  package.json
Labels: renovate

#3995 chore(deps): update dependency cypress to v3.4.1
  package-lock.json
  package.json
Labels: renovate

#4029 chore(deps): update dependency marked to v0.7.0
  package-lock.json
  package.json
Labels: renovate

#4035 chore(deps): update react
  package-lock.json
  package.json
Labels: renovate

#4036 chore(deps): update dependency mini-css-extract-plugin to v0.8.0
  package-lock.json
  package.json
Labels: renovate

#4041 DCOS-57484: make Quota header buttons consistent with Services
  plugins/services/src/js/containers/services/ServicesQuotaView.tsx
  tests/pages/services/QuotaOverview-cy.js
Labels: Bug Fix

#4044 DCOS-50935: TypeError: t.reduce is not a function
  plugins/services/src/js/reducers/serviceForm/PortMappings.js
Labels: Bug Fix

#4045 DCOS-48222: TypeError: Failed to execute 'selectAllChildren' on 'Selection': parameter 1 is not of type 'Node'.
  src/js/components/ClickToSelect.js
Labels: Bug Fix

#4028 DCOS-57423: Quota Detail view is not scrollable
  plugins/services/src/js/containers/services/ServicesQuotaView.tsx
Labels: Bug Fix

#4052 DCOS-57482: Quota - Remove "no limit" badges & banner from ServicesTable
  plugins/services/src/js/columns/ServicesTableNameColumn.tsx
  plugins/services/src/js/containers/services/ServiceTreeView.js
  plugins/services/src/js/containers/services/ServicesTable.js
  tests/pages/services/ServiceTable-cy.js
Labels: hold merge

#4064 DCOS-50331: TypeError: Cannot convert undefined or null to object
  plugins/services/src/js/utils/VipLabelUtil.js
  plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js
Labels: Bug Fix

#4056 DCOS-21165 Assign Automatically Host port checkbox is not in line for multi container apps
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
Labels: Bug Fix

#4022 DCOS-57015: Jobs - Enable/Disable Schedule sets concurrencyPolicy to ALLOW
  plugins/jobs/src/js/data/__tests__/JobModel-test.js
  plugins/jobs/src/js/types/JobSchedule.ts
  src/js/events/MetronomeClient.ts
Labels: Bug Fix

#4067 chore(deps): update dependency @types/recompose to v0.30.7
  package-lock.json
  package.json
Labels: renovate

#4065 chore(deps): update dependency @types/react to v16.9.1
  package-lock.json
  package.json
Labels: renovate

#4079 chore(deps): update dependency tslint to v5.19.0
  package-lock.json
  package.json
Labels: renovate

#4082 chore(deps): update graphql
  package-lock.json
  package.json
Labels: renovate

#4083 Components filter styling
  src/styles/views/packages/styles.less
Labels: Bug Fix

#4081 chore(deps): update dependency @types/react to v16.9.2
  package-lock.json
  package.json
Labels: renovate

#4086 chore(deps): update semantic-release monorepo
  package-lock.json
  package.json
Labels: renovate

#4087 chore(deps): update webpack
  package-lock.json
  package.json
Labels: renovate

#4090 fix(deps): update dependency classnames to v2.2.6
  package-lock.json
  package.json
Labels: renovate

#4085 chore(deps): update jest
  package-lock.json
  package.json
  src/js/components/__tests__/__snapshots__/SplitPanel-test.js.snap
  src/js/components/modals/__tests__/__snapshots__/LanguagePreferenceFormModal-test.js.snap
Labels: renovate

#4068 DCOS-49571: Services Table > Resume Service modal has an incomplete error description
  plugins/services/src/js/components/modals/ServiceResumeModal.js
  plugins/services/src/js/components/modals/ServiceScaleFormModal.js
  plugins/services/src/js/utils/ServiceActionModalsUtil.ts
  plugins/services/src/js/utils/__tests__/ServiceActionModalsUtil-test.js
Labels: Bug Fix

#4093 fix(deps): update dependency compare-versions to v3.5.1
  package-lock.json
  package.json
Labels: renovate

#4095 fix(deps): update dependency md5 to v2.2.1
  package-lock.json
  package.json
  packages/@extension-kid/notification-service/package.json
Labels: renovate

#4094 fix(deps): update dependency cookie to v0.4.0
  package-lock.json
  package.json
Labels: renovate

#4097 fix(deps): update dependency prop-types to v15.7.2
  package-lock.json
  package.json
Labels: renovate

#4099 fix(deps): update dependency react-jsonschema-form to v1.8.0
  package-lock.json
  package.json
Labels: renovate

#4100 fix(deps): update dependency reflect-metadata to v0.1.13
  package-lock.json
  package.json
Labels: renovate

#4098 chore(deps): update dependency typescript to v3.6.2
  package-lock.json
  package.json
  plugins/jobs/src/js/components/form/helpers/MetronomeJobValidators.ts
Labels: renovate

#4070 Max-width to breadcrumb text
  plugins/services/src/js/components/ServiceBreadcrumbs.js
  src/styles/layout/page-header/breadcrumbs/styles.less
Labels: No Pressure

#4101 fix(deps): update dependency rxjs to v6.5.2
  package-lock.json
  package.json
Labels: renovate

#4096 fix(deps): update dependency objektiv to v0.5.0
  package-lock.json
  package.json
  src/js/utils/DataValidatorUtil.js
  webpack/webpack.config.js
Labels: renovate

#4103 chore(deps): update commitlint monorepo to v8 (major)
  package-lock.json
  package.json
Labels: renovate

#4105 chore(deps): update dependency autoprefixer to v9
  package-lock.json
  package.json
Labels: renovate

#4104 chore(deps): update dependency @types/events to v3
  package-lock.json
  package.json
  packages/cosmos-client/package-lock.json
  packages/cosmos-client/package.json
Labels: renovate

#4106 chore(deps): update dependency babel-eslint to v10
  package-lock.json
  package.json
Labels: renovate

#4111 chore(deps): update dependency junit-merge to v2
  package-lock.json
  package.json
Labels: renovate

#4109 chore(deps): update dependency inversify to v5
  package-lock.json
  package.json
  packages/@extension-kid/notification-service/package.json
  packages/@extension-kid/toast-notifications/package.json
Labels: renovate

#4107 chore(deps): update dependency esprima to v4
  package-lock.json
  package.json
Labels: renovate

#4110 chore(deps): update @dcos
  package-lock.json
  package.json
  packages/cosmos-client/package-lock.json
  packages/cosmos-client/package.json
  packages/dcos-ui-update-client/package.json
Labels: renovate

#4112 fix(deps): update dependency graphql to v14.5.4
  package-lock.json
  package.json
Labels: renovate

#4117 chore(deps): update dependency postcss to v7
  package-lock.json
  package.json
Labels: renovate

#4119 chore(deps): update dependency rxjs-marbles to v5
  package-lock.json
  package.json
Labels: renovate
