Repository dcos/dcos-ui, pull requests merged in 2019-01, with the labels that each got.

#3486 CompositeStore remove addMarathonApps
  plugins/services/src/js/stores/MarathonStore.js
  src/js/structs/CompositeState.js
  src/js/structs/__tests__/CompositeState-test.js
Labels: No Pressure

#3488 [spike day] DCOS-21203: Volumes size label is uppercase and shouldn't be
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/forms/VolumesFormSection.js
Labels: No Pressure

#3439 DCOS-21270: Create service puts cursor at wrong position in app id box
  plugins/services/src/js/components/forms/GeneralServiceFormSection.js
Labels: No Pressure

#3489 [spike day] DCOS-34504: Align LDAP Authentication radio buttons
  locale/en/messages.json
  locale/zh/messages.json
  src/styles/components/form-elements/styles.less
Labels: No Pressure

#3448 DCOS-46048: [1.11] COPS-3759 affecting dcos-ui: When no nodes are in the cluster the message should have different wording
  plugins/nodes/src/js/pages/NodesOverview.js
Labels: COPS, No Pressure

#3440 DCOS-44594: COPS-3759 affecting dcos-ui: When no nodes are in the cluster the message should have different wording
  locale/en/messages.json
  locale/zh/messages.json
  plugins/nodes/src/js/pages/NodesAgents.js
Labels: COPS

#3443 DCOS-41059: Deleting groups in Services has a misleading message
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/modals/DisabledGroupDestroyModal.js
  tests/pages/services/ServiceTable-cy.js
Labels: No Pressure

#3499 DCOS-43909 SDK Plans Client
  plugins/services/src/js/data/ServicePlansClient.ts
  plugins/services/src/js/data/__tests__/ServicePlansClient-test.ts
  plugins/services/src/js/data/__tests__/_fixtures/service-plan-in-progress.json
Labels: ready to review

#3500 DCOS-44818: add script that detects .only statements
  scripts/utils/test
Labels: ready to review

#3528 chore(deps): update dependency @dcos/tslint-config to v0.1.1
  package-lock.json
  package.json
Labels: renovate

#3536 DCOS-47374 fix: icons for local development
  package.json
  src/js/index.js
Labels: No Pressure, ready to review

#3546 DCOS-47514: [1.13] COPS-4345 affecting dcos-ui: Change "Unavailable" status text for External Volumes
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/constants/VolumeStatus.js
  plugins/services/src/js/utils/__tests__/MarathonUtil-test.js
Labels: COPS

#3533 DCOS-47175: Update Table component in nodes page
  package-lock.json
  package.json
  plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
  plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
  plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
  plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
  plugins/nodes/src/js/columns/NodesTableIpColumn.tsx
  plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
  plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
  plugins/nodes/src/js/columns/NodesTableSpacingColumn.tsx
  plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
  plugins/nodes/src/js/columns/NodesTableTypeColumn.tsx
  plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
  plugins/nodes/src/js/columns/__tests__/__snapshots__/NodesTableHealthColumn-test.js.snap
  plugins/nodes/src/js/components/NodesTable.tsx
  src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap
Labels: ready to review

#3496 [COPS] DCOS_OSS-4633: [1.13] dcos6 network is shown as available for UCR in the UI.
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/components/forms/NetworkingFormSection.js
  tests/_fixtures/mesos/overlay-master.json
  tests/pages/networking/Networks-cy.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: COPS

#3555 [COPS] DCOS_OSS-4632: [1.12] dcos6 network is shown as available for UCR in the UI.
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/components/forms/NetworkingFormSection.js
  tests/_fixtures/mesos/overlay-master.json
  tests/pages/networking/Networks-cy.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: COPS

#3556 [COPS] DCOS_OSS-4631: [1.11] dcos6 network is shown as available for UCR in the UI.
  plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
  plugins/services/src/js/components/forms/NetworkingFormSection.js
  tests/_fixtures/mesos/overlay-master.json
  tests/pages/networking/Networks-cy.js
  tests/pages/services/ServiceFormModal-cy.js
Labels: COPS

#3541 [spike] DCOS-47444: [1.13] Deployment bubble-help shows confusing numbers.
  locale/en/messages.json
  locale/zh/messages.json
  plugins/services/src/js/components/ServiceStatusIcon.js
Labels: No Pressure

#3537 [spike] DCOS-46611: [1.12] Cannot read property 'stateTypes' of undefined
  src/js/structs/Node.js
Labels: No Pressure

#3561 chore(system-tests): fix dev.sh config
  system-tests/driver-config/dev.sh
Labels: ready to review

#3562 Integration Flakes
  system-tests/universe/test-universe.js
  tests/pages/services/ServiceActions-cy.js
  tests/pages/services/ServiceDetail-cy.js
  tests/pages/services/ServiceFormModal-cy.js
  tests/pages/services/TasksTable-cy.js
Labels: ready to review

#3571 DCOS-47960 Publish nightly dcos-ui as "nightly" instead of "2.24.4"
  universe/package.json
Labels: No Pressure, ready to review
